### ISSUE TITLE
GetWatchlist needs to return Ratings as well

### ISSUE THREAD

**Issue by rohanbrohan** [svbrodersen/CSC207_project#63]
Need to change the output data of get watchlist usecase to have a ratings hashmap attribute, so all movies in the watchlist with a rating can have that rating displayed. 

Also, Use case Interactor can trim the ratings hashmap to only include Movies that are in the watchlist list as well.

**Comment by sgspencer2618** [comment]
<img width="866" alt="image" src="https://github.com/svbrodersen/CSC207_project/assets/144366072/c35d11aa-7869-437a-828e-565d0a7f2faf">

Here's the hash map trimmer - does this all look good?

**Comment by sgspencer2618** [comment]
<img width="850" alt="image" src="https://github.com/svbrodersen/CSC207_project/assets/144366072/c2ff35e0-7105-43f5-91ad-ba18a0b7189e">
revised implementation*
